name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs_on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi 
        run: echo "hello"