name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" 
      - name: update pip
        run: pip3 install --upgrade pip
      - name: install all dependencies
        run: pip3 install -r requirements.txt
      - name: test with pytest
        run: |
          pip3 install pytest
          pytest

     