name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME=localhost
      DATABASE_PORT=5432
      DATABASE_PASSWORD=postgresql
      DATABASE_NAME=fastapi
      DATABASE_USERNAME=postgres
      SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=30
    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" 
      - name: update pip
        run: pip3 install --upgrade pip
      - name: install all dependencies
        run: pip3 install -r requirements.txt
      - name: test with pytest
        run: |
          pip3 install pytest
          pytest

     